name: flutter_assessment
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  intl: ^0.20.1

  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
